### ISSUE TITLE
README "Deploy to IBM Cloud" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#11]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, change the following in the "Deploy to IBM Cloud" section of the README:

- [x] Change the "Deploy to IBM Cloud" button source URL.
- [x] Change the "Deploy to IBM Cloud" button link URL.
- [x] Update the app name.
- [x] Update the prefix name.
- [x] Document the service(s) created by the deployment.
- [x] Test the "Deploy to IBM Cloud" button to ensure it works as expected.

**Comment by ptitzler** [comment]
Not sure what app name and prefix name refer to

**Comment by bradley-holt** [comment]
@ptitzler There are `[app-name]` and `[chosen prefix]` placeholders in that section of the template. It looks like those have been addressed, so I've checked them off here in the issue description.
