### ISSUE TITLE
README "Run locally" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#12]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, change the following in the "Run locally" section of the README:

- [ ] Change the repo name in the "clone the repo" section.
- [ ] Change the "install the prerequisites" section as needed.
- [ ] Change the "run the server" section as needed.
- [ ] Change the "Create a Cloudant or CouchDB service" section as needed.

**Comment by glynnbird** [comment]
This is also part of https://github.com/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb/pull/22

**Comment by glynnbird** [comment]
@bradley-holt Roger that
