### ISSUE TITLE
README "Database and replication setup" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#13]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, change the following in the "Database and replication setup" section of the README:

- [x] Ensure that the referenced screenshots are added to the repository.
- [x] Change the "create the remote database" section as needed.
- [x] Change the "enable CORS" section as needed.
- [x] Change the "set the replication target" section as needed.

**Comment by ptitzler** [comment]
The image https://github.com/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb/blob/master/doc/source/images/enable_cors.png is referring to the wrong app.

**Comment by lornajane** [comment]
Moving back to "In Progress" as I can't see what needs reviewing here.

**Comment by bradley-holt** [comment]
LGTM. Moving to "Done" pipeline.
