### ISSUE TITLE
README "Using the app" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#14]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, change the following in the "Using the app" section of the README:

- [x] Change the introductory section as needed.
- [x] Ensure that the referenced screenshot is added to the repository.
- [ ] Write the "running the app" section. (NOT NEEDED, replaced by *Run locally* section)
- [x] Write the "running the tests" section.
- [x] Write the "deploying to GitHub Pages" section.

**Comment by rajrsingh** [comment]
Probably better for someone else to grab this so I can focus on React
