### ISSUE TITLE
README "Privacy Notice" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#15]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, update the "Privacy Notice" section of the README as needed.

**Comment by ptitzler** [comment]
Privacy notice links to master copy. The Tracking removal instructions are already up-to-date.

**Comment by lornajane** [comment]
Is this marked for review because no changes are needed?  I'm not sure what should be reviewed.  I think the Privacy Notice should be added with the metrics tracker since that's what it relates to, but I see the issues were unlinked.  Is there something I'm missing here?

**Comment by bradley-holt** [comment]
The instructions say to remove this line:

    require('metrics-tracker-client').track();

However, the actual line of code is slightly different in syntax (double versus single quotes and no semicolon):

    require("metrics-tracker-client").track()

We should either update the instructions or update line of code so that they two are identical.

**Comment by bradley-holt** [comment]
@ptitzler Can you address the inconsistency that I've identified in the previous comment?
