### ISSUE TITLE
Apache License

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#18]
- [ ] Ensure that a `LICENSE` file has been added that licenses this code under the Apache License 2.0.
- [ ] Ensure that a "License" section is included in the README, using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference.

**Comment by glynnbird** [comment]
1) A `LICENSE` file does exist
2) a License section is added in https://github.com/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb/pull/22

**Comment by lornajane** [comment]
This looks like it's done, thanks @glynnbird
