### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#19]
Using the [CONTRIBUTING template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/CONTRIBUTING.md) for reference, create a `CONTRIBUTING.md` file with the following:

- [ ] Welcoming introduction
- [ ] Proposing new features section
- [ ] Fixing bugs section
- [ ] Merge approval section
- [ ] Setup section

**Comment by lornajane** [comment]
Merged
