### ISSUE TITLE
Integrate Deployment Tracking

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#21]
Integrate deployment tracking with the new metrics tracker maintained by the Digital Business Group.

**Comment by lornajane** [comment]
it isn't clear from the Metrics Tracker information whether this makes sense on a client-side application https://github.com/IBM/metrics-collector-service#clients

**Comment by ptitzler** [comment]
Follow the instructions in https://github.com/IBM/metrics-collector-client-node to enable tracking.
