### ISSUE TITLE
Enable IBM Cloud Deployment

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#24]
Enable deployment to IBM Cloud. This should be implemented as a Node.js app that serves static files, likely using Express. The Polymer + PouchDB implementation can be use for reference:
https://github.com/ibm-watson-data-lab/shopping-list-polymer-pouchdb/blob/master/app.js

Note that this is just one deployment option. The app can still be deployed to GitHub Pages or simply run locally.

**Comment by lornajane** [comment]
This looks like no further review is needed since the associated pull request was already merged, but I see in channel that there are some issues with the deploy to cloud button.  What's the state of play?  Is further work needed to get the deploy to cloud working?

**Comment by bradley-holt** [comment]
It appears that the DevOps toolchains team does not recommend using declared services in the `manifest.yml` file anymore. This is because the DevOps pipeline only evaluates the `manifest.yml` file once (upon pipeline creation), and therefore does not pick up any changes that may be introduced after that. DevOps toolchains team instead recommends a custom pipeline that creates the services in a deploy script. I recommend we consider this issue closed, as it _should_ work on first deployment, and we open a new issue for creating a custom pipeline.
