### ISSUE TITLE
Create a Custom DevOps Toolchan

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#46]
Declare a custom DevOps toolchain within a `toolchain.yml` file that creates the backing service(s) needed. Also remove the `declared-services` section of the `manifest.yml`. This is to resolve a problem identified in #24. See this documentation for reference:
https://console.bluemix.net/docs/services/ContinuousDelivery/deploy_button.html

**Comment by ptitzler** [comment]
A draft implementation is available in the https://github.com/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb/tree/i46 branch.

**Comment by ptitzler** [comment]
The following two documents depict the workflow:

[deployment flow with custom toolchain](https://github.com/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb/files/1661572/deployment.flow.pdf)

[deployment flow with legacy deployment code ](https://github.com/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb/files/1661570/default_deployment_flow.pdf)

**Comment by bradley-holt** [comment]
The argument _for_ this DevOps toolchain approach (as opposed to the current declared services in `manifest.yml` approach) is that the DevOps toolchains team does not recommend using declared services in the `manifest.yml` file anymore (see comment in #24). This is because the DevOps pipeline only evaluates the `manifest.yml` file once (upon pipeline creation), and therefore does not pick up any changes that may be introduced after that. DevOps toolchains team instead recommends a custom pipeline that creates the services in a deploy script. **Do we want to go with the more supported DevOps toolchain approach or the less supported yet simpler declared services in `manifest.yml` approach?**

**Comment by markstur** [comment]
I have so far stuck w/ the simpler aint-broke-don't-fix old style, but I'd be happy to see you boldly go forward with the new recommendation.  Most people will be glad to skip the clone and eclipse IDE. Also, if you iron out the details, then I can copy your approach when the old way stops working. That said, probably go with whatever @ptitzler is happier with.

**Comment by bradley-holt** [comment]
@ptitzler I'me fine with abandoning this approach (and sticking with declared services) if that's your inclination.

**Comment by bradley-holt** [comment]
Closing as won't fix.
