### ISSUE TITLE
Produce Demo Video

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#49]
- [x] Produce a short demo video (example: https://youtu.be/hsq0sUAM-1I)
- [x] Add a "Watch the Video" section to the README (example: https://github.com/ibm-watson-data-lab/shopping-list-polymer-pouchdb/blob/master/README.md#watch-the-video)

**Comment by vabarbosa** [comment]
demo video has been produced. waiting to get it published/posted before adding link in the README.
