### ISSUE TITLE
512x512 icon missing

### ISSUE THREAD

**Issue by glynnbird** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#8]
In your manifest file you reference a 512x512 icon which isn't there.

- either remove the reference from manifest.json
- or, add a 512x512 icon

I only noticed because I'm copying your service worker ;)

**Comment by glynnbird** [comment]
Noting that PWAs require 512x512 icons, so I guess that's option (2)

**Comment by vabarbosa** [comment]
my bad.. should be all set now. thanks
