### ISSUE TITLE
README Badges

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vanillajs-pouchdb#9]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, add badges to the top of the README being sure to:

- [x] Change the "Build Status" badge repository source URL.
- [x] Change the "Build Status" badge repository link URL.
- [x] Change the "IBM Cloud Deployments" badge tracking number in the URL.

**Comment by ptitzler** [comment]
Markdown for build status: [![Build Status](https://travis-ci.org/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb.svg?branch=master)](https://travis-ci.org/ibm-watson-data-lab/shopping-list-vanillajs-pouchdb)

**Comment by lornajane** [comment]
Moving to in progress as this appears to be blocked.

**Comment by bradley-holt** [comment]
Confirmed that all of the URLs are correct.
